services:
  # Traefik reverse proxy
  traefik:
    image: traefik:v2.10
    container_name: apphub-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=apphub-network"
      - "--providers.docker.watch=true"
      - "--providers.docker.refreshseconds=15"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--accesslog.format=json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    networks:
      - apphub-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    restart: unless-stopped

  # Python LangGraph service
  ai-service:
    build:
      context: ../apps/ai-service
      dockerfile: Dockerfile.dev
    container_name: apphub-ai-service
    volumes:
      - ../apps/ai-service:/app
      - ../logs/ai-service:/app/logs
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG
    networks:
      - apphub-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-service.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.ai-service.entrypoints=web"
      - "traefik.http.routers.ai-service.middlewares=ai-service-stripprefix"
      - "traefik.http.middlewares.ai-service-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.services.ai-service.loadbalancer.server.port=8000"
      - "traefik.docker.network=apphub-network"
    restart: unless-stopped

  # Next.js web application
  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    container_name: apphub-web
    volumes:
      - ../apps/web:/app/apps/web
      - ../logs/web:/app/logs
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost/api
    networks:
      - apphub-network
    depends_on:
      - ai-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.docker.network=apphub-network"
    restart: unless-stopped

networks:
  apphub-network:
    driver: bridge 